// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eojtsxwqarybirpyyugx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVvanRzeHdxYXJ5YmlycHl5dWd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzMjk0NTQsImV4cCI6MjA2MTkwNTQ1NH0.pAj9zQHSHvfdGxiCA4xpj9qsqdaF9SN0WeOJnBbPVtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);